# add other example programs as needed

all:
	(cd bilayer; $(MAKE))
	(cd geom; $(MAKE))
	(cd test; $(MAKE))
	(cd verify; $(MAKE))

clean:
	(cd bilayer; $(MAKE) clean)
	(cd geom; $(MAKE) clean)
	(cd test; $(MAKE) clean)
	(cd verify; $(MAKE) clean)
